name: 'Hello World'
description: 'Greet someone using other actions'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: Greet with an Action Package
      uses: immutable-actions/e2e-test-public-org-accessible-action@0.0.3
      with:
        who-to-greet: ${{ inputs.who-to-greet }}

